version: "3.8"

services: 
  postgres:
    container_name: money-count-postgres
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file: ./etc/db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ['-c', 'log_statement=all']
      
volumes:
  db-data:
